export const Collections = {
  counters: "counters",
  organizations: "organizations",
  subscriptionPlans: "subscription_plans",
  users: "users",
  employees: "employees",
  employeeInvites: "employee_invites",
  projects: "projects",
  projectMembers: "project_members",
  tasks: "tasks",
  taskParticipants: "task_participants",
  subtasks: "subtasks",
  taskTags: "task_tags",
  taskTagRelations: "task_tag_relations",
  timeEntries: "time_entries",
  taskActivity: "task_activity",
  taskAttachments: "task_attachments",
  employeeDocuments: "employee_documents",
  formerEmployees: "former_employees",
  formerEmployeeDocuments: "former_employee_documents",
  notifications: "notifications",
  workSessions: "work_sessions",
  workBreaks: "work_breaks",
  timeApprovalRequests: "time_approval_requests",
  leaveRequests: "leave_requests",
  leaveUsageOverrides: "leave_usage_overrides",
  publicHolidays: "public_holidays",
  workLocations: "work_locations",
  orgAttendanceQr: "org_attendance_qr",
  orgAttendanceQrActivity: "org_attendance_qr_activity",
  appSettings: "app_settings",
  customers: "customers",
  invoices: "invoices",
  bankAccounts: "bank_accounts",
  ledgerAccounts: "ledger_accounts",
  estimates: "estimates",
  payments: "payments",
  expenses: "expenses",
  contracts: "contracts",
  vendorBills: "vendor_bills",
  dashboardReminders: "dashboard_reminders",
} as const;

export type CollectionName = (typeof Collections)[keyof typeof Collections];
