export const Collections = {
  counters: "counters",
  organizations: "organizations",
  users: "users",
  employees: "employees",
  employeeInvites: "employee_invites",
  projects: "projects",
  projectMembers: "project_members",
  tasks: "tasks",
  taskParticipants: "task_participants",
  subtasks: "subtasks",
  taskTags: "task_tags",
  taskTagRelations: "task_tag_relations",
  timeEntries: "time_entries",
  taskActivity: "task_activity",
  taskAttachments: "task_attachments",
  employeeDocuments: "employee_documents",
  formerEmployees: "former_employees",
  formerEmployeeDocuments: "former_employee_documents",
  notifications: "notifications",
  workSessions: "work_sessions",
  workBreaks: "work_breaks",
  timeApprovalRequests: "time_approval_requests",
  leaveRequests: "leave_requests",
  leaveUsageOverrides: "leave_usage_overrides",
  publicHolidays: "public_holidays",
  appSettings: "app_settings",
  customers: "customers",
  invoices: "invoices",
} as const;

export type CollectionName = (typeof Collections)[keyof typeof Collections];
